emrServerless {
  enabled = false
  enabled = ${?CONFIG_SERVICE_APPLICATION_EMR_SERVERLESS_ENABLED}
  region = "ap-south-1"
  region = ${?CONFIG_SERVICE_APPLICATION_EMR_SERVERLESS_REGION}
  applicationId = ${?CONFIG_SERVICE_APPLICATION_EMR_SERVERLESS_APPLICATION_ID}
  jobRoleArn = ${?CONFIG_SERVICE_APPLICATION_EMR_SERVERLESS_JOB_ROLE_ARN}
  executionRoleArn = ${?CONFIG_SERVICE_APPLICATION_EMR_SERVERLESS_EXECUTION_ROLE_ARN}
}
