import { QueryExecutionState } from "../../RealTimeQuery.interface";

/**
 * Props for the AiQuery component
 */
export interface AiQueryProps {
  /** Current query value */
  query: string;
  /** Callback when query value changes */
  onQueryChange: (query: string) => void;
  /** Callback when the user submits an AI query */
  onExecute: (naturalLanguageQuery: string) => void;
  /** Callback to cancel the running query */
  onCancel: () => void;
  /** Current execution state */
  executionState: QueryExecutionState;
  /** Whether a query is currently running */
  isLoading: boolean;
  /** The SQL generated by the AI (if available) */
  generatedSql: string | null;
}

