/**
 * Data Pipeline Visual Component
 * Shows the flow: All Events → Sampled → Features → Sent to Pulse
 */

import { Box, Text, Skeleton, Tooltip, Paper, Group } from "@mantine/core";
import { IconArrowRight, IconInfoCircle } from "@tabler/icons-react";
import { DataPipelineProps } from "../../SamplingConfig.interface";
import classes from "../../SamplingConfig.module.css";

const STAGE_EXPLANATIONS = {
  "All Events":
    "Total events generated by your app before sampling is applied.",
  "After Sampling":
    "Events kept based on your session sample rate (random % of sessions).",
  "Feature Gates":
    "Each feature has its own independent sample rate. This shows the combined effect of enabled features.",
  "Sent to Pulse":
    "Final estimated count of events that will be transmitted to Pulse servers.",
};

export function DataPipeline({ stats, isLoading }: DataPipelineProps) {
  const formatNumber = (num: number): string => {
    if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
    if (num >= 1000) return `${(num / 1000).toFixed(0)}K`;
    return num.toString();
  };

  const stages = [
    {
      label: "All Events",
      value: stats.totalEvents,
      percent: 100,
      type: "active" as const,
      dropAfter: stats.samplingDropRate,
    },
    {
      label: "After Sampling",
      value: stats.afterSampling,
      percent: Math.round((stats.afterSampling / stats.totalEvents) * 100),
      type: "active" as const,
      dropAfter: stats.featureDropRate,
    },
    {
      label: "Feature Gates",
      value: stats.afterFeatures,
      percent: Math.round((stats.afterFeatures / stats.totalEvents) * 100),
      type: "active" as const,
      dropAfter: 0,
    },
    {
      label: "Sent to Pulse",
      value: stats.finalSent,
      percent: stats.totalSentRate,
      type: "sent" as const,
      dropAfter: 0,
    },
  ];

  if (isLoading) {
    return (
      <Box className={classes.pipelineSection}>
        <Box className={classes.pipelineContainer}>
          {[1, 2, 3, 4].map((i) => (
            <Box key={i} style={{ display: "flex", alignItems: "center" }}>
              <Skeleton height={80} width={100} radius="md" />
              {i < 4 && <Skeleton height={20} width={40} mx="xs" />}
            </Box>
          ))}
        </Box>
      </Box>
    );
  }

  return (
    <Box className={classes.pipelineSection}>
      {/* Pipeline explanation header */}
      <Paper
        p="sm"
        mb="lg"
        radius="md"
        style={{ backgroundColor: "#f0f9ff", border: "1px solid #bae6fd" }}
      >
        <Group gap="xs" mb={4}>
          <IconInfoCircle size={16} style={{ color: "#0284c7" }} />
          <Text size="sm" fw={600} c="blue.7">
            How Data Flows Through Your Configuration
          </Text>
        </Group>
        <Text size="xs" c="gray.7">
          Events pass through multiple stages before reaching Pulse:
          <strong> Sampling</strong> randomly selects a percentage of sessions.
          <strong> Features</strong> operate independently with their own sample
          rates. Configure each stage below.
        </Text>
      </Paper>

      <Box className={classes.pipelineContainer}>
        {stages.map((stage, index) => (
          <Box
            key={stage.label}
            style={{ display: "flex", alignItems: "center" }}
          >
            <Tooltip
              label={
                STAGE_EXPLANATIONS[
                  stage.label as keyof typeof STAGE_EXPLANATIONS
                ]
              }
              position="top"
              multiline
              w={220}
              withArrow
            >
              <Box className={classes.pipelineStage}>
                <Box
                  className={`${classes.pipelineStageBox} ${stage.type === "sent" ? classes.sent : classes.active}`}
                >
                  <Text className={classes.pipelineStageLabel}>
                    {stage.label}
                  </Text>
                  <Text className={classes.pipelineStageValue}>
                    {formatNumber(stage.value)}
                  </Text>
                  <Text className={classes.pipelineStagePercent}>
                    {stage.percent}%
                  </Text>
                </Box>
              </Box>
            </Tooltip>

            {index < stages.length - 1 && (
              <Box className={classes.pipelineArrow}>
                <IconArrowRight size={24} />
                {stage.dropAfter > 0 && (
                  <Tooltip
                    label={`${stage.dropAfter}% of events dropped at this stage`}
                    withArrow
                  >
                    <Text className={classes.pipelineDropBadge}>
                      -{stage.dropAfter}%
                    </Text>
                  </Tooltip>
                )}
              </Box>
            )}
          </Box>
        ))}
      </Box>

      <Text ta="center" size="sm" c="dimmed" mt="md">
        Estimated monthly:{" "}
        <strong style={{ color: "#059669" }}>
          {formatNumber(stats.finalSent)}
        </strong>{" "}
        events sent ({stats.totalSentRate}% of total) —{" "}
        <Text span size="xs" c="dimmed">
          Hover over stages to learn more
        </Text>
      </Text>
    </Box>
  );
}
