backend:
  - "backend/**"

ui:
  - "pulse-ui/**"

android-sdk:
  - "pulse-android-otel/**"

rn-sdk:
  - "pulse-react-native-otel/**"

deploy:
  - "deploy/**"

docs:
  - "**/*.md"

ci:
  - ".github/**"