import type {
  CrashIssue,
  ANRIssue,
  NonFatalIssue,
} from "./AppVitals.interface";

export const MOCK_CRASHES: CrashIssue[] = [
  {
    id: "crash-1",
    title: "NullPointerException",
    message: "NullPointerException in MainActivity.onCreate() at line 42",
    errorMessage: "NullPointerException in MainActivity.onCreate() at line 42",
    stackTrace: "at com.example.MainActivity.onCreate...",
    affectedUsers: 1245,
    occurrences: 3420,
    firstSeen: "2025-11-01",
    lastSeen: "2025-11-07",
    appVersion: "2.4.0",
    osVersion: "Android 13",
    device: "Samsung Galaxy S23",
    trend: [10, 12, 15, 18, 14, 16, 19],
  },
  {
    id: "crash-2",
    title: "ArrayIndexOutOfBoundsException",
    message: "ArrayIndexOutOfBoundsException in DataProcessor.process()",
    errorMessage: "ArrayIndexOutOfBoundsException in DataProcessor.process()",
    stackTrace: "at com.example.DataProcessor.process...",
    affectedUsers: 892,
    occurrences: 2103,
    firstSeen: "2025-11-03",
    lastSeen: "2025-11-07",
    appVersion: "2.3.5",
    osVersion: "Android 12",
    device: "Google Pixel 7",
    trend: [8, 10, 12, 11, 13, 15, 12],
  },
  {
    id: "crash-3",
    title: "OutOfMemoryError",
    message: "OutOfMemoryError during image loading in ImageCache",
    errorMessage: "OutOfMemoryError during image loading in ImageCache",
    stackTrace: "at com.example.ImageLoader.load...",
    affectedUsers: 543,
    occurrences: 1234,
    firstSeen: "2025-11-05",
    lastSeen: "2025-11-07",
    appVersion: "2.4.0",
    osVersion: "Android 11",
    device: "OnePlus 9",
    trend: [5, 6, 8, 9, 7, 8, 10],
  },
  {
    id: "crash-4",
    title: "IllegalStateException",
    message: "IllegalStateException: Fragment not attached to Activity",
    errorMessage: "IllegalStateException: Fragment not attached to Activity",
    stackTrace: "at com.example.fragments.ProfileFragment...",
    affectedUsers: 321,
    occurrences: 876,
    firstSeen: "2025-11-02",
    lastSeen: "2025-11-07",
    appVersion: "2.4.0",
    osVersion: "Android 13",
    device: "Xiaomi 12",
    trend: [4, 5, 6, 5, 7, 8, 6],
  },
  {
    id: "crash-5",
    title: "ClassCastException",
    message: "ClassCastException in RecyclerView adapter binding",
    errorMessage: "ClassCastException in RecyclerView adapter binding",
    stackTrace: "at com.example.adapters.FeedAdapter...",
    affectedUsers: 234,
    occurrences: 567,
    firstSeen: "2025-11-04",
    lastSeen: "2025-11-07",
    appVersion: "2.3.5",
    osVersion: "Android 12",
    device: "Samsung Galaxy A54",
    trend: [3, 4, 5, 4, 6, 5, 7],
  },
];

export const MOCK_ANRS: ANRIssue[] = [
  {
    id: "anr-1",
    title: "Main thread blocked",
    message: "Main thread blocked for 8.2s in NetworkCall.execute()",
    anrMessage: "Main thread blocked for 8.2s in NetworkCall.execute()",
    affectedUsers: 678,
    occurrences: 1520,
    firstSeen: "2025-11-02",
    lastSeen: "2025-11-07",
    appVersion: "2.4.0",
    osVersion: "Android 13",
    device: "Xiaomi 12",
    trend: [7, 8, 10, 9, 11, 12, 10],
  },
  {
    id: "anr-2",
    title: "UI thread unresponsive",
    message: "UI thread unresponsive during database query for 12.5s",
    anrMessage: "UI thread unresponsive during database query for 12.5s",
    affectedUsers: 421,
    occurrences: 892,
    firstSeen: "2025-11-04",
    lastSeen: "2025-11-07",
    appVersion: "2.3.5",
    osVersion: "Android 12",
    device: "Samsung Galaxy A54",
    trend: [5, 6, 7, 6, 8, 9, 7],
  },
  {
    id: "anr-3",
    title: "Input dispatching timeout",
    message: "Input dispatching timed out after 15.3s",
    anrMessage: "Input dispatching timed out after 15.3s",
    affectedUsers: 234,
    occurrences: 543,
    firstSeen: "2025-11-05",
    lastSeen: "2025-11-07",
    appVersion: "2.4.0",
    osVersion: "Android 11",
    device: "OnePlus 9",
    trend: [3, 4, 5, 4, 6, 5, 7],
  },
];

export const MOCK_NON_FATALS: NonFatalIssue[] = [
  {
    id: "nonfatal-1",
    title: "Failed to load remote config",
    message: "Failed to load remote config from server",
    errorMessage: "Failed to load remote config from server",
    type: "Network Error",
    issueType: "Network Error",
    affectedUsers: 2341,
    occurrences: 8920,
    firstSeen: "2025-11-01",
    lastSeen: "2025-11-07",
    appVersion: "2.4.0",
    osVersion: "Android 13",
    device: "Various",
    trend: [15, 18, 20, 19, 22, 25, 23],
  },
  {
    id: "nonfatal-2",
    title: "Image cache write failed",
    message: "Image cache write failed - disk space insufficient",
    errorMessage: "Image cache write failed - disk space insufficient",
    type: "IO Exception",
    issueType: "IO Exception",
    affectedUsers: 1023,
    occurrences: 3421,
    firstSeen: "2025-11-03",
    lastSeen: "2025-11-07",
    appVersion: "2.3.5",
    osVersion: "Android 12",
    device: "Various",
    trend: [10, 12, 14, 13, 16, 18, 15],
  },
  {
    id: "nonfatal-3",
    title: "JSON parsing error",
    message: "JSON parsing error in API response",
    errorMessage: "JSON parsing error in API response",
    type: "Parse Error",
    issueType: "Parse Error",
    affectedUsers: 876,
    occurrences: 2134,
    firstSeen: "2025-11-02",
    lastSeen: "2025-11-07",
    appVersion: "2.4.0",
    osVersion: "Android 13",
    device: "Various",
    trend: [8, 10, 12, 11, 14, 16, 13],
  },
  {
    id: "nonfatal-4",
    title: "Database transaction timeout",
    message: "Database transaction timeout",
    errorMessage: "Database transaction timeout",
    type: "Database Error",
    issueType: "Database Error",
    affectedUsers: 654,
    occurrences: 1876,
    firstSeen: "2025-11-04",
    lastSeen: "2025-11-07",
    appVersion: "2.3.5",
    osVersion: "Android 12",
    device: "Various",
    trend: [6, 8, 10, 9, 12, 14, 11],
  },
];
