app {
    pulseServerUrl = ${CONFIG_SERVICE_APPLICATION_PULSESERVERURL}
    shutdownGracePeriod = 5
    serviceJwtSecret = ${?CONFIG_SERVICE_APPLICATION_SERVICEJWTSECRET}
    clickhouseHost = ${CONFIG_SERVICE_APPLICATION_CLICKHOUSEHOST}
    clickhousePort = ${CONFIG_SERVICE_APPLICATION_CLICKHOUSEPORT}
    clickhouseDatabase = ${CONFIG_SERVICE_APPLICATION_CLICKHOUSEDATABASE}
    clickhouseUsername = ${CONFIG_SERVICE_APPLICATION_CLICKHOUSEUSERNAME}
    clickhousePassword = ${CONFIG_SERVICE_APPLICATION_CLICKHOUSEPASSWORD}
    redisHost = ${CONFIG_SERVICE_APPLICATION_REDISHOST}
    redisPort = ${CONFIG_SERVICE_APPLICATION_REDISPORT}
}