{
  "type": "record",
  "name": "StackTraceEvent",
  "namespace": "org.dreamhorizon.pulseserver",
  "fields": [
    {"name": "Timestamp", "type": {"type": "long", "logicalType": "timestamp-micros"}},
    {"name": "EventName", "type": "string"},
    {"name": "Title", "type": "string"},
    {"name": "ExceptionStackTrace", "type": "string"},
    {"name": "ExceptionStackTraceRaw", "type": "string"},
    {"name": "ExceptionMessage", "type": "string"},
    {"name": "ExceptionType", "type": "string"},
    {"name": "Interactions", "type": {"type": "array", "items": "string"}},
    {"name": "ScreenName", "type": "string"},
    {"name": "UserId", "type": "string"},
    {"name": "SessionId", "type": "string"},
    {"name": "Platform", "type": "string"},
    {"name": "OsVersion", "type": "string"},
    {"name": "DeviceModel", "type": "string"},
    {"name": "AppVersionCode", "type": "string"},
    {"name": "AppVersion", "type": "string"},
    {"name": "SdkVersion", "type": "string"},
    {"name": "BundleId", "type": "string"},
    {"name": "TraceId", "type": "string"},
    {"name": "SpanId", "type": "string"},
    {"name": "GroupId", "type": "string"},
    {"name": "Signature", "type": "string"},
    {"name": "Fingerprint", "type": "string"},
    {"name": "ScopeAttributes", "type": {"type": "map", "values": "string"}},
    {"name": "LogAttributes", "type": {"type": "map", "values": "string"}},
    {"name": "ResourceAttributes", "type": {"type": "map", "values": "string"}},
    {"name": "ProjectId", "type": "string"},
    {"name": "PulseType", "type": "string"},
    {"name": "MeteringSessionId", "type": "string"},
    {"name": "AppInstallationId", "type": "string"}
  ]
}
