ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
# TODO-ios: Remove this once we have a proper PulseSDK podspec
PULSE_SDK_PATH = '/Users/shubhamgupta/D11Repo/temps/main-pulse/pulse-ios-sdk'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'PulseReactNativeOtelExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  # TODO-ios: Remove this once we have a proper PulseSDK podspec
  # Core dependencies (required by PulseKit)
  pod 'Pulse-Swift-Protocol-Exporter-Common', :path => "#{PULSE_SDK_PATH}"
  pod 'Pulse-Swift-Protocol-Exporter-Http', :path => "#{PULSE_SDK_PATH}"
  pod 'Pulse-Swift-SdkResourceExtension', :path => "#{PULSE_SDK_PATH}"
  pod 'Pulse-Swift-Instrumentation-NetworkStatus', :path => "#{PULSE_SDK_PATH}"
  pod 'Pulse-Swift-Instrumentation-URLSession', :path => "#{PULSE_SDK_PATH}"
  pod 'Pulse-Swift-Instrumentation-Interaction', :path => "#{PULSE_SDK_PATH}"
  pod 'Pulse-Swift-Sessions', :path => "#{PULSE_SDK_PATH}"
  pod 'Pulse-Swift-SignPostIntegration', :path => "#{PULSE_SDK_PATH}"
  
  # Main PulseKit SDK
  pod 'PulseKit', :path => "#{PULSE_SDK_PATH}"

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
