ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
else
  Pod::UI.puts "Configuring Pod with dynamically linked Frameworks".green
  use_frameworks!
end

target 'PulseReactNativeOtelExample' do
  config = use_native_modules!

  # In order to test locally, add path to exact pulse-ios-sdk folder. 
  # For source code noting else is required.
  # For pointing any local framework no need to change anything here, follow steps mentioned in PulseIOSExample README.md for change in pulse-ios-sdk folder.
  pod 'PulseKit', :path => '<absolute-path-to>/pulse-ios-sdk/'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    pulse_deps = ['OpenTelemetry-Swift-Api', 'OpenTelemetry-Swift-Sdk', 'SwiftProtobuf', 'KSCrash']
    installer.pods_project.targets.each do |target|
      if pulse_deps.any? { |dep| target.name.start_with?(dep) }
        target.build_configurations.each do |bc|
          bc.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
        end
      end
    end
  end
end
