#!/bin/bash
set -e  # Exit on error

# Log all output
exec > >(tee /var/log/user-data.log) 2>&1
echo "Starting user-data script at $(date)"

# Set environment variables persistently
# Write to /etc/environment for system-wide availability (systemd, all processes)
# Write to /etc/profile.d/ for interactive shell sessions
echo "Setting up environment variables..."

# Create /etc/environment entries (system-wide, no export needed)
ENV_FILE="/etc/environment"
# Backup existing file
if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$ENV_FILE.backup"
fi

# Remove existing Pulse environment variables to avoid duplicates
%{ for env_var in env_vars ~}
sed -i '/^${env_var.key}=/d' "$ENV_FILE" 2>/dev/null || true
%{ endfor ~}

# Append environment variables to /etc/environment
%{ for env_var in env_vars ~}
echo "${env_var.key}=${replace(env_var.value, "'", "'\\''")}" >> "$ENV_FILE"
%{ endfor ~}

# Create profile.d script for interactive shells
PROFILE_SCRIPT="/etc/profile.d/pulse-env.sh"
cat > "$PROFILE_SCRIPT" << 'PROFILE_HEADER'
# Pulse application environment variables
# This file is automatically generated by user-data script
PROFILE_HEADER

# Append export statements to profile.d script
%{ for env_var in env_vars ~}
echo "export ${env_var.key}='${replace(env_var.value, "'", "'\\''")}'" >> "$PROFILE_SCRIPT"
%{ endfor ~}

chmod 644 "$PROFILE_SCRIPT"

# Export in current session for use during script execution
%{ for env_var in env_vars ~}
export ${env_var.key}='${replace(env_var.value, "'", "'\\''")}'
%{ endfor ~}

# Update system packages
echo "Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

# Install required packages
echo "Installing required packages..."
apt-get install -y \
    git \
    curl \
    wget \
    unzip \
    ca-certificates \
    gnupg \
    lsb-release

# Install Java 17 JDK (Eclipse Temurin)
echo "Installing Java 17 JDK..."
apt-get install -y software-properties-common
add-apt-repository -y ppa:adoptopenjdk/maven || true
apt-get update -y

# Install OpenJDK 17
apt-get install -y openjdk-17-jdk

# Verify Java installation
java -version
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export PATH=$PATH:$JAVA_HOME/bin

# Install Maven 3.9
echo "Installing Maven 3.9..."
MAVEN_VERSION=3.9.9
cd /tmp
wget https://archive.apache.org/dist/maven/maven-3/$${MAVEN_VERSION}/binaries/apache-maven-$${MAVEN_VERSION}-bin.tar.gz
tar -xzf apache-maven-$${MAVEN_VERSION}-bin.tar.gz
mv apache-maven-$${MAVEN_VERSION} /opt/maven
rm apache-maven-$${MAVEN_VERSION}-bin.tar.gz

# Set Maven environment variables
export M2_HOME=/opt/maven
export PATH=$PATH:$M2_HOME/bin

# Add to profile for persistence
cat >> /etc/profile.d/maven.sh << 'EOF'
export M2_HOME=/opt/maven
export PATH=$PATH:$M2_HOME/bin
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
export PATH=$PATH:$JAVA_HOME/bin
EOF

chmod +x /etc/profile.d/maven.sh
source /etc/profile.d/maven.sh

# Verify Maven installation
mvn -version

# Clone the repository to /opt/bin
echo "Cloning pulse repository to /opt/bin..."
mkdir -p /opt/bin
cd /opt/bin
if [ -d "pulse" ]; then
    rm -rf pulse
fi
git clone https://github.com/dream-horizon-org/pulse.git
cd pulse

# Checkout main branch (ensure we're on main)
git checkout main

# Build the backend server
echo "Building pulse-server..."
cd backend/server

# Build with Maven (skip tests and checkstyle for faster build)
mvn clean package -DskipTests -Dcheckstyle.skip=true

# Verify JAR was created
if [ ! -f "target/pulse-server/pulse-server.jar" ]; then
    echo "ERROR: JAR file not found at target/pulse-server/pulse-server.jar"
    exit 1
fi

# Run the application directly from the cloned directory
echo "Starting pulse-server..."
cd /opt/bin/pulse/backend/server

# Run in background with nohup so it continues after script exits
nohup java \
    -Dlogback.configurationFile=/opt/bin/pulse/backend/server/src/main/resources/logback/logback-docker.xml \
    -jar /opt/bin/pulse/backend/server/target/pulse-server/pulse-server.jar \
    run org.dreamhorizon.pulseserver.verticle.MainVerticle \
    > /opt/bin/pulse/backend/server/pulse-server.log 2>&1 &

# Save the PID
echo $! > /opt/bin/pulse/backend/server/pulse-server.pid

# Wait a moment for application to start
sleep 10

# Check if the process is running
if ps -p $(cat /opt/bin/pulse/backend/server/pulse-server.pid) > /dev/null 2>&1; then
    echo "✓ pulse-server started successfully (PID: $(cat /opt/bin/pulse/backend/server/pulse-server.pid))"
    
    # Wait a bit more for application to fully start
    echo "Waiting for application to be ready..."
    sleep 15
    
    # Check if port 8080 is listening
    if netstat -tlnp 2>/dev/null | grep -q ':8080' || ss -tlnp 2>/dev/null | grep -q ':8080'; then
        echo "✓ Application is listening on port 8080"
    else
        echo "⚠ Warning: Port 8080 may not be listening yet"
    fi
else
    echo "⚠ Warning: pulse-server process may not have started properly"
    echo "Check logs at: /opt/bin/pulse/backend/server/pulse-server.log"
    if [ -f /opt/bin/pulse/backend/server/pulse-server.log ]; then
        echo "Recent log output:"
        tail -n 50 /opt/bin/pulse/backend/server/pulse-server.log || true
    fi
fi

# Clean up temporary Maven download
echo "Cleaning up temporary files..."
rm -rf /tmp/apache-maven-*

echo "User-data script completed at $(date)"
echo "Pulse server should be running on port 8080"
echo "Application directory: /opt/bin/pulse/backend/server"
echo "Log file: /opt/bin/pulse/backend/server/pulse-server.log"
echo "PID file: /opt/bin/pulse/backend/server/pulse-server.pid"
echo "To check if running: ps -p \$(cat /opt/bin/pulse/backend/server/pulse-server.pid)"
echo "To view logs: tail -f /opt/bin/pulse/backend/server/pulse-server.log"
