"""Session-scoped RCA structured report v1."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

SessionRcaMetricIdV1 = Literal["session_score", "volume"]


class DegradingInteractionV1(BaseModel):
    """Injected by runner from Java payload; not generated by the LLM."""

    model_config = ConfigDict(populate_by_name=True)

    interaction_name: str = Field(alias="interactionName")
    interaction_count: int = Field(alias="interactionCount")
    avg_apdex: float = Field(alias="avgApdex")
    degradation_weight: float = Field(alias="degradationWeight")


class SessionRcaMetricRowV1(BaseModel):
    metric_id: SessionRcaMetricIdV1
    metric_label: str
    value_display: str
    baseline_display: str
    delta_display: str
    value_number: float | None = None
    baseline_number: float | None = None


class SessionRcaStructuredSegmentV1(BaseModel):
    rank: int = Field(ge=1, description="1-based rank among segments.")
    title: str = Field(description="Copy the segment label exactly, e.g. 'platform: Android'.")
    impact: str = Field(description='"critical" or "normal"; echo from payload, do not override.')
    metrics: list[SessionRcaMetricRowV1] = Field(
        description="Exactly 2 rows in order: session_score (Apdex) then volume.",
    )
    insights: str | None = Field(
        default=None,
        description="One sentence explaining what makes this segment notable.",
    )
    affected_sessions: list[str] | None = Field(
        default=None,
        description="Up to 2 session IDs with session_score below the critical threshold.",
    )


class SessionRcaStructuredV1(BaseModel):
    """LLM output for session-scoped quality RCA — structured format."""

    version: int = Field(default=1, ge=1, le=1)
    executive_summary: str = Field(
        ...,
        description=(
            "Up to 4 sentences: overall session quality assessment, worst segment, "
            "scope of impact when clear from volumes."
        ),
    )
    segments: list[SessionRcaStructuredSegmentV1] = Field(
        default_factory=list,
        max_length=8,
        description="One entry per returned segment, ordered by severity (critical first).",
    )
    recommendations: list[str] = Field(
        ...,
        min_length=3,
        max_length=7,
        description="Short actionable strings grounded in segment data.",
    )


# ── Response-layer models (runner-injected fields; NOT part of the Gemini output schema) ──────────

class SessionRcaStructuredSegmentResponseV1(SessionRcaStructuredSegmentV1):
    """Segment with runner-injected evidence fields added after LLM generation."""

    degrading_interactions: list[DegradingInteractionV1] | None = None


class SessionRcaStructuredResponseV1(BaseModel):
    """Final response model enriched with runner-injected data."""

    version: int
    executive_summary: str
    segments: list[SessionRcaStructuredSegmentResponseV1]
    recommendations: list[str]

    @classmethod
    def from_llm_output(cls, structured: SessionRcaStructuredV1) -> "SessionRcaStructuredResponseV1":
        return cls(
            version=structured.version,
            executive_summary=structured.executive_summary,
            segments=[
                SessionRcaStructuredSegmentResponseV1(**seg.model_dump())
                for seg in structured.segments
            ],
            recommendations=structured.recommendations,
        )
