import { CriticalInteractionDetailsFilterOptionsResponse } from "./getCriticalInteractionDetailsFilterOptions.interface";

export const getCriticalInteractionDetailsFilterOptions =
  async (): Promise<CriticalInteractionDetailsFilterOptionsResponse> => {
    // TODO: Make an API request to get this details.
    return new Promise((resolve) =>
      resolve({
        PLATFORM: ["androidplaystore", "androidfull", "ios"],
        APP_VERSION: [
          "5.42.0",
          "5.42.1",
          "5.42.2",
          "5.43.0",
          "5.43.1",
          "5.43.2",
          "5.44.0",
          "5.44.1",
          "5.44.2",
          "5.45.0",
        ],
        NETWORK_PROVIDER: [
          "Enet",
          "ERONET",
          "JIO 4G | BSNL MOBILE",
          "405872",
          "Mobily RAMADAN SEASON",
          "405858",
          "I TIM",
          "405 874",
          "Vi India | Idua",
          "Vi India | V! India",
          "Swisscom",
          "stc ksa GLMC2025 | airtel",
          "Beeline AM",
          "42102",
          "e& | International",
          "mts",
          "BSNL Mobiles",
          "uninor",
          "405753",
          "Sunrise",
          "Orange RDC",
          "Airtel,",
          "Beeline KG",
          "Rogers",
          "XL-AXIATA",
          "Optus AU",
          "bMobile",
          "Airtel | TATA DOCOMO",
          "40411",
          "GEO-GEOCELL",
          "E& | Vodafone IN",
          "entel",
          "KCELL",
          "Tele2 RU",
          "e& | Idea",
          "MOBILY GLMC2025 | airtel",
          "Mobile Communications Company of Iran",
          "MTN-UGANDA",
          "sim24",
          "510 11",
          "LAO TELECOM",
          "Vodafone Essar",
          "Celcom Wifi Call",
          "e& |  ",
          "INDIAN RAILWAYS",
          "Reliance | airtel",
          "Salt",
          "404 15",
          "ORANGE BF",
          "Orange CD",
          "40478",
          "MOR IAM",
          "410961",
          "VN VINAPHONE",
          "Orange B",
          "HALOTEL",
          "GOLIS",
          "40484",
          "43410",
          "CHILI",
          "Vоdafоne",
          "BSNLMOBILE",
          "MESHAL AL-EZZ",
          "C&W SEY",
          "MegaFon",
          "Turk Telekom",
          "MBZSAT e& |  ",
          "a鲴el",
          "SYRIATEL",
          "DIGICEL",
          "Airtel_HP | airtel",
          "airtel |  irtel",
          "কোনো পরিষেবা নেই৷",
          "Telkom-Stay Safe",
          "Ucell | airtel",
          "AIRCEL",
          "aiztel",
          "Vodafonu IN",
          "কোনো পরিষেবা নেই",
          "Jio True5G",
          "IND AirTel",
          "Omantel",
          "MTN",
          "!dea",
          "du | airtel",
          "epic",
          "OOREDOO",
          "airtel | mobily",
          "MOOV AFRICA CI",
          "404 89",
          "MobiFone",
          "TATA(DOCOMO",
          "BTB-Mobile",
          "Mint",
          "404 100",
          "40459",
          "CellOne",
          "glo ng",
          "Mobily GLMC2025",
          "zain SA",
          "MTRADE",
          "Ind-Jio",
          "Safaricom",
          "DITO",
          "zain KW",
          "MTS Armenia",
          "Unitel",
          "Zain IQ",
          "Mobily IGF2024",
          "MEO",
          "MOVITEL",
          "TATA",
          "TUNTEL",
          "KUWAIT 25-26 Ooredoo",
          "ChampionsBahrain",
          "CELTEL",
          "CLARO",
          "404 971",
          "40415",
          "WATANIYA",
          "40422",
          "STC | mobily",
          "MBZSAT e& | Idea",
          "VIL",
          "Zain KSA",
          "Vi India | !dea",
          "502158",
          "vodafone",
          "OMAN MOBILE",
          "Mobily GLMC2025 ",
          "Mtrade",
          "Cellone | BSNL Mobile",
          "Almadar",
          "aivtel",
          "vodafone NL",
          "mobilis",
          "Orange EG",
          "Airtel SC",
          "air�el",
          "I䥡",
          "फक्त आणीबाणीचे क",
          "DSTCom",
          "DIALOG",
          "Vi India,",
          "Idea - Be Safe",
          "40439",
          "Red Bull MOBILE | Vi India",
          "CellOne | DOLPHIN",
          "Mobily GIDDAM",
          "405857",
          "",
          "Lebara",
          "BSNL MOBILE",
          "STC KSA",
          "Airtel | airtel",
          "Zain KW",
          "CHINA MOBILE",
          "VodaCom-SA",
          "019",
          "Vodafone IN | Vi India",
          "ફક્ત તાત્કાલિક કૉલ્સ",
          "HUMANS",
          "dea",
          "SaveNaAirtelMoney",
          "Digi",
          "ɤga",
          "41099",
          "IND-JIO | Jio 4G",
          "AIRTEL | PLATINUM",
          "40451",
          "akrtel",
          " my.t ",
          "RO Vodafone RO",
          "Airtel 5G | salam mobile",
          "Airtel | Vodafone",
          "BSNL Mob",
          "404 980",
          "JIO",
          "Vi",
          "JIO 4G | Jio",
          "MBZSAT - du",
          "Mobily RALLY HAIL",
          "Yettel",
          "LG U+",
          "idea",
          "DIGITEL",
          "IDEA | Vi India",
          "JIO 4G,",
          "MBZSAT e& | International",
          "  Digi  ",
          "405 752",
          "O2.CZ",
          "VIVO",
          "STC KSA RAMADAN SEASON",
          "Max it ton app pour payer transferer...",
          "Vi is here | Idea",
          "Hexcom India",
          "40416",
          "40420",
          "केवल आपातकालीन क",
          "etisalat",
          "UzTelecom",
          "TW Mobile",
          "O!",
          "STC | airtel",
          "MTN CAMEROON",
          "Asiacell",
          "Airtel | AirTel",
          "du | Vodafone IN",
          "stc Kuwait",
          "Teletalk",
          "IND INDOSAT",
          "ROGERS",
          "42606",
          "AIS-T",
          "TH 3G+",
          "SMARTY",
          "46059",
          "TEAM",
          "Far EasTone",
          "Airtel_HP | Airtel",
          "salam mobile | airtel",
          "AT&T | airtel",
          "JIO4G",
          "केवल आपातकालीन कॉल",
          "telenor",
          "Orange SN",
          "MTN ZM",
          "MOBILY ESPORTS WORLD CUP",
          "Vodafone IN | airtel",
          "vodafone ES",
          "vodafone P",
          "F-Bouygues Telecom",
          "40449",
          "Aquafon",
          "IDEA | !dea",
          "Red Bull MOBILE",
          "Airtel\u0011HP",
          "MY CelcomDigi",
          "Orange BF",
          "SAF FOR YOU",
          "mobily ",
          "Batelco",
          "Vodafone Essar - Gujarat Limited",
          "40470",
          "Red Bull MOBILE | airtel",
          "Cablenet",
          "Talk2all",
          "405 799",
          "Vi is here | Vodafone IN",
          "ayrtel",
          "460 59",
          "ਕੋਈ ਸਰਵਿਸ ਨਹੀਂ",
          "404 88",
          "Voda",
          "TNM",
          "TELKOMSEL",
          "T-MOBILE PL",
          "3 AT",
          "405861",
          "stc BH",
          "STAY AT HOME",
          " VIVA",
          "Airtel Nigeria",
          "MTN SHUKRAN",
          "HOTMOBILE",
          "Smart",
          "Ethio telecom",
          "AIRTEL | zain BH",
          "MegaFon RUS",
          "Yas",
          "3 UK",
          "iD",
          "Swazi-MTN",
          "Telecel",
          "Ultra",
          "MY CELCOMDIGI",
          "Vodafone Qatar | Vodafone IN",
          "DTAC.BETTER TOGETHER",
          "404 979",
          "MOBILY SAUDI 2034 BID",
          "MOBILY RAMADAN SEASON",
          "TIM",
          "Vi India | Hutch",
          ",JIO 4G",
          "Airtel_HP",
          "AirTel",
          "Rakuten",
          "फक्त आणीबाणीचे कॉल",
          "U Mobile",
          "TASHICELL",
          "my.t",
          "Proximus",
          "KDDI",
          "EMTEL-MRU",
          "SberMobile",
          "Airtel\u0011HP | airtel",
          "VF-QA",
          "t2 rus",
          "Orange_Egypt",
          "STAY AT HOME | BSNL MOBILE",
          "BSNL M_Φ_É",
          "40400",
          "Beeline KZ",
          "SEATEL",
          "405864",
          "405 67",
          "DOLPHIN",
          "Digi.Mobil",
          "R-CELL",
          "JIO 4G | airtel",
          "VIVA",
          "CELLONE-North",
          "CLARO BR",
          "airt l",
          "405 521",
          "Jazz",
          "Banglalink",
          "Singtel",
          "Umniah",
          "VI HR",
          "vodafone IE",
          "vodafone UK",
          "BSNL | BSNL Mobile",
          "41004",
          "International",
          "$_\n@@£òBILE",
          "airten",
          "AWCC",
          "40554",
          "t2❄",
          "africell",
          "TuneTalk",
          "VIVA KW",
          "ETL",
          "YES OPTUS",
          "mobily  | airtel",
          "Dolphin | BSNL MOBILE",
          "Verizon ",
          "stc ksa IMPAQ",
          "40440",
          "ILIAD",
          "Vi Indiane",
          "Ooredoo | airtel",
          "MOOV AFRICA ",
          "Orange LBR",
          "Dhiraagu",
          "Zain JO",
          "Telkomsel",
          "KT, VIVA",
          "Vodafone OM",
          "AirtelTanzania",
          "MTN Zambia",
          "4KA SK",
          "KT",
          "405 66",
          "Només trucades d'emergència",
          "MTN NG",
          "vodafone IT",
          "Yes 4G",
          "404 87",
          "NOS",
          "CellOne | Jio",
          "Virgin | airtel",
          "Yas ",
          "I ea",
          "STAY AT HOME | BSNL Mobile",
          "Ooredoo",
          "Virgin",
          "China Unicom",
          "कोई नेटवर्क सेवा",
          "Partner",
          "OrangeCaresAboutYou",
          "40431",
          "Digitel",
          "airtel | Ncell",
          "Nepal Telec",
          "TELEKOM.RO",
          "stc ksa | airtel",
          "Searching for Service",
          "404 112",
          "Lebara KSA 93",
          "3 IRL",
          "63513",
          "405865",
          "Reliance | Vi India",
          "IND-JIO | Vi India",
          "BSNL",
          "3",
          "Robi",
          "VodafoneIdea",
          "VIRGIN",
          ",airtel",
          "Orange GN",
          "IND airtel | airtel",
          "Djezzy",
          "CELLONE | BSNL MOBILE",
          "AEinnovate ETISALAT",
          "DishNet SS",
          "eirtel",
          "Yota",
          "VI INDIA 4G",
          "airtq½W덅æKì",
          "One HU",
          "salam mobile",
          "TIGO GH",
          "Cellcom IL",
          "BASE",
          "MTN GH",
          "MTN NIGERIA",
          "HelloSIM",
          "CelebrateBahrain",
          "Yes",
          "digi",
          "IDEA MP",
          "cirtel",
          "ALTICE",
          "F SFR",
          "LV TELE2",
          "No service",
          "stc KW",
          "UZB Ucell",
          "Uztelecom",
          "Friendi Mobile",
          "NT 3G",
          "TATA DOCOMO",
          "China Mobile",
          "Camtel",
          "BSNL Mobkle",
          "JIO 4G Maharashtra ",
          "Vodacom Congo",
          "NTC",
          "MTN Nigeria",
          "PROGRESIF",
          "Vodafone RO",
          "One.al",
          "405869",
          "ROSHAN",
          "சேவை இல்லை.",
          "404 11",
          "Nationwide",
          "Airtel KE",
          "Telkom SA",
          "£Σ¿Ω@_@Vi India",
          "MOBILY HAJJ EXPO | airtel",
          "IDEA | Idea",
          "  MOBILY TEACHER DAY",
          "Telekom SK",
          "Maxis",
          "vodafone GH",
          "405 852",
          "Zain 4.5G+",
          "MOBILY GLMC2025",
          "Vi India | VIL",
          "Orange",
          "Zamtel",
          "SLTMobitel",
          "Roshan",
          "TRUE-H",
          "Mobily Hajj Expo | airtel",
          "Partner | airtel",
          "Vodafone QA",
          "ETL Mobile",
          "Telstra",
          "GOMO",
          "TELCEL",
          "BSNL MOFILE",
          "A1",
          "Celcom",
          "41051",
          "stc ksa Hajj Expo | airtel",
          "#StaySafe - Smart",
          "40410",
          "winSIM",
          "IND airtel,",
          "JIO 4\u0003",
          "ZainJO",
          "MY MAXIS",
          "MTN Rwandacell",
          "Mobily Hajj Expo ",
          "airtml",
          "OMANTEL",
          "40445",
          "t2",
          "Turkcell",
          "mt:s",
          "Fastlink",
          "Digicel",
          "Al Madar",
          "Lucky",
          "ASIACELL | airtel",
          "Cellone | CellOne",
          "Telenor PK",
          "MPT",
          "40493",
          "405856",
          "40552",
          "Airtel | Idea",
          "airtel",
          "Jio",
          "ViIndia",
          "CELLONE-East",
          " zain IQ",
          "TELENOR",
          "Mytel",
          "Vi India | IDEA",
          "Vi is here | Vi India",
          "stc ksa GLF24",
          "Bharti Airtel",
          "MTN-SA",
          "DhiMobile",
          "MTC NAM",
          "Vodafone(IN",
          "432 11",
          "405 756",
          "A1 HR ",
          "MOBILY RALLY HAIL | airtel",
          "CELLONE | BSNL Mobile",
          "MegaFon TJK",
          "405862",
          "_è_Φ_É",
          "T-Mobile",
          "AIRTEL",
          "DHIRAAGU",
          "Renna Mobile",
          "MOBILY RALLY HAIL",
          "VodafoneQatar | airtel",
          "du | Jio",
          "Mobifone",
          "No service.",
          "vodafone.de",
          "airuel",
          "ooredoo | airtel",
          "NT 3G | Jio",
          "Eswatini Mobile",
          "BAHRAIN POLICE DAY",
          "410090",
          "Orange SK",
          "કોઈ સેવા નથી.",
          "CELLONE",
          "Zain GLMC2025",
          "YES FT5G",
          "Cellfie",
          "QCELL",
          "Airtel NG",
          "Nepal Telecom | airtel",
          "CU",
          "Telenor",
          "VN MobiFone",
          "Vodafone CZ",
          "GLOBE",
          "405868",
          "stc ksa RIYADH METRO",
          "SAMANTEL",
          "Zain GAINSUMMIT2024",
          "Zain SA",
          "Airtel 5G | airtel",
          "ooredoo",
          "zain BH",
          "Rogers Wireless",
          "Fido",
          "Red Bull Mobile",
          "MTN Eswatini",
          "UMS-UZB",
          "SoftBank",
          "Mobily GLMC2025 | airtel",
          "UZO",
          "stc ksa | Vi India",
          "RJO",
          "MOBILY SAUDI34",
          "swyp",
          "MTN RWANDA",
          "404 60",
          "404 05",
          "CELTIIS",
          "40465",
          "INDOSAT",
          "Airtel 5G",
          "stc",
          "Ooredoo Maldives PVT LTD",
          "heya",
          "KUWAIT 25-26 Oor",
          "YOTA",
          "EE",
          "Ncell | airtel",
          "Glo NG",
          "KHALEEJI ZAIN 26",
          "JIO 4G | Jio 4G",
          "Mobitel",
          "ALG Mobilis",
          "Airtel Stay Home",
          "Airtel GA",
          "63310",
          "IND-JIO | Vodafone IN",
          "AeroMobile",
          "40454",
          "405863",
          "MY CELCOM 3G",
          "JIO4G | Jio",
          "Etisalat",
          "Viettel",
          "Tele2",
          "Salam Mobile",
          "MOBIUZ",
          "Namaste",
          "Mobily IMPAQ",
          "Mascom",
          "MOBILY IMPAQ",
          "TANGO",
          "Orange TN",
          "amrtel",
          "STC | Vi India",
          "Vi India",
          "stc ksa GLMC2025",
          "MY CELCOM",
          "Zain",
          "CellOne | BSNL MOBILE",
          "ZAIN BH",
          "imagine",
          "BSNL-ICR",
          "404 13",
          "000000",
          "JIO 4G | BSNL Mobile",
          "IN-DOLPHIN | BSNL MOBILE",
          "IND-JIO | airtel",
          "du | Vi India",
          "Mobitel LK | Idea",
          "40567",
          "40419",
          "MBZSAT e&",
          "सेवा नाही.",
          "Zain Hajj Expo",
          "Orange JO",
          "Airtel Zambia",
          "V! India",
          "dtac-T.Better Together",
          "Idua",
          "Viva",
          "Odido",
          "42206",
          "T-Mobile.pl",
          "Sin servicio",
          "Free",
          "Vi India,Vi India",
          "Airtel | Vi India",
          "TSEL-PEMILUDAMAI",
          "Tesco - SK",
          "Orange MA",
          "IDEA | airtel",
          "STC",
          "IND-JIO | Jio",
          "A1 SRB",
          "Mobily RALLY HAIL ",
          "Vi India,JIO 4G",
          "dtac.Better Together",
          "Telemach",
          "Cell C",
          "Itea",
          "Vodafone IN | VIL",
          'BSNL MOBILE | BSNL"MOBILE',
          "TIMBRASIL",
          "Telus",
          "LTT",
          "Telenor ",
          "Telia N",
          "VERY",
          "Zain WORLD CAMEL DAY",
          "Reliance Jio",
          "AVEA",
          "Vodafone IN",
          "Emergency calls only",
          "MTS",
          "Emtel",
          "BSNL 3G",
          "t2🎄",
          "qirtel",
          "Airtel | PLAUINUM",
          "BSNL MOBILE | BSNL Mobile",
          "VODAFONE OMAN",
          "we",
          "AIS",
          "ಯಾವುದೇ ಸೇವೆಯಿಲ್ಲ",
          "MOVISTAR",
          "Iliad",
          "404 920",
          "Epic",
          "AIRTEL | airtel",
          "STC | Vodafone IN",
          "VODAFONE IN",
          "Zain GLOBAL CSR FORUM",
          "405871",
          "zain SA | airtel",
          "Digi IT",
          "Ucom",
          "VodafoneAL",
          "BOOST",
          "LAO GSM",
          "60801",
          "Android",
          "du",
          "mobily",
          "zain IQ",
          "Vietnamobile",
          "RBM-Oman",
          "Verizon",
          "Airtel CD",
          "404999",
          "Airtel | telenor",
          "Zain KSA | airtel",
          "ø",
          "NL KPN",
          "404 12",
          "5G .. Soon",
          "airtel | PLATINUM",
          "stc ksa",
          "कोई नेटवर्क सेवा नहीं",
          "e&",
          "AT&T",
          "TashiCell",
          "000000 | Vi India",
          "Team",
          "SKTelecom",
          "HOT MOBILE",
          "Airtel Zambia | airtel",
          "42010",
          "Airtel UG",
          "Irancell",
          "M1",
          "Magenta-T-",
          "40494",
          "CMHK",
          "imagine\r",
          "elisa",
          "IDEA | VodafoneIdea",
          "Glo Mobile",
          "IDEA | Vi",
          "Virgin | Virgin Mobile",
          "Ooredoo7",
          "40455",
          "Mobily Hajj Expo",
          "Vodafone Qatar",
          "BATELCO",
          "BeelineKG",
          "BSNL | BSNL MOBILE",
          "CHN-UNICOM",
          "MBZSAT E& | Vodafone IN",
          "MOTIV",
          "MTS RUS",
          "SGP-M1",
          "Ide",
          "Vi Inlya",
          "Vodafone-Be Safe",
          "Telekom.de",
          "SAFARICOM",
          "stc ksa RALLY HAIL | Vi India",
          "TelkomSA-R",
          "40468",
          "IL Pelephone",
          "CELTEL GA",
          "Reliance | Jio",
          "airtel | TATA DOCOMO",
          "404 205",
          "MAXIS-STAYHOME",
          "ENet",
          "NTT DOCOMO",
          "BSNL mobile",
          "SIMBA",
          "Vi India | Vi",
          "Plus",
          "M:TEL",
          "Ooredoo | Vi India",
          "Vodacom",
          "HT HR",
          "DIGITEL\r",
          "DJ EVATIS",
          "Vodafone Oman",
          "NT 3G | airtel",
          "404979",
          "Tigo Ghana",
          "eir",
          "BSNL Mobile",
          "IND-JIO",
          "Yettel SRB",
          "Hormuud Telecom",
          "beeline",
          "Mobily-KSA",
          "IND AirTel | Airtel",
          "404 24",
          "Vodafone Fiji",
          "STC KSA HAJJ EXPO",
          "Nepal Telecom | Jio",
          "orange",
          "MATTEL",
          "IND airtel,JIO 4G",
          "Zain GLOBAL HEALTH",
          "JIO 4G | Vi India",
          "Airtel | PLATINUM",
          "40495",
          "TRUE-H 3G+",
          "Telstra Mobile",
          "IDEA",
          "stc ksa RALLY HAIL",
          "KOREK",
          "Zain KW | airtel",
          "EMTEL",
          "UMNIAH",
          "US Mobile",
          "Dolphin-Delhi",
          "+Movil",
          "405859",
          "\u001b/",
          "2degrees",
          "Ufone",
          "zain SA | Vi India",
          "stc ksa GLMC2025 | Vi India",
          "65503",
          "Orange F",
          "airtel,",
          "HOT mobile",
          "BTC",
          "VinaPhone",
          "MBZSAT e& | airtel",
          "41005",
          "Airtel | Jio",
          "Vodafone- Be Safe",
          "LoneStar Cell",
          "ISAT-PEMILU DAMAI",
          "JIO4G | Vi India",
          "Jio 4G",
          "Idea",
          "IND AirTel | airtel",
          "Ooredoo TN",
          "YES",
          "Beeline",
          "404 44",
          "mobily | airtel",
          "BT B-Mobile",
          "cellcard",
          "Verizon Wireless",
          "STC KSA RALLY HAIL",
          "MTN Rwanda",
          "Tigo",
          "No service | Jio",
          "AIRTEL | telenor",
          "FLOW",
          "40444",
          "Mobitel LK",
          "Vodafone",
          "Airtel",
          "Virgin Mobile",
          "LycaMobile",
          "Ucell",
          "Uninor",
          "Reliance",
          "false",
          "IDEA | Vodafone IN",
          " CSL ",
          "MEGA",
          "Play",
          "Airtel Uganda",
          "404 909",
          "stc ksa IGF2024",
          "Metfone",
          "$A! $oF ¥ £q £",
          "True-T",
          "dtac-T",
          "e& | airtel",
          "Georg ",
          "Tamim a",
          "activ",
          "ZAINJO",
          "GUY GTT + Do More",
          "MBZSAT E&",
          " zain BH",
          "Libyana",
          "JIO 4G,airtel",
          "Zain BIBAN24",
          "Bell",
          "40548",
          "Airtel TZ",
          "ᩲtel",
          "INDOSATOOREDOO",
          "aistel",
          "Aircel",
          "UZMOBILE",
          "STC KSA SAUDIMEDIAFORUM",
          "TIGOHND",
          "SFR",
          "T-Mobile UK",
          "Ideq",
          "40551",
          "999150",
          "alo",
          "UNITEL",
          "E&",
          "ZONG",
          "TIGO",
          "t2 Black",
          "AIRTEL |  irtel",
          "MBZSAT - du | airtel",
          "405840",
          "Airtel | Ncell",
          "Π $A! $oF £é ¥où",
          "Taiwan Mobile",
          "SCOM-PK",
          "Cellcom",
          "404 94",
          "Idea Cellular",
          "MBZSAT E& | Vi India",
          "40490",
          "Africell",
          "U MOBILE",
          "Grameenphone",
          "Dialog",
          "DST",
          "ZAIN KSA",
          "BSNL Mobile | BSNL MOBILE",
          "Vodafone Qatar | Jio",
          "Mobily RALLY HAIL | airtel",
          "stc ksa RALLY HAIL | airtel",
          "40555",
          "EtisalatNigeria",
          "Swazi Mobile",
          "OMAN MOBILE | airtel",
          "Ooredo",
          "Tesco Mobile",
          "airtul",
          "AFRICELL",
          "e& etisalat and",
          "MBZSAT E& | BSNL MOBILE",
          "FOUNDING DAY",
          "JIO 4G | Vi",
          "40450",
          "Vodafone IN | Idea",
          "Hutch",
          "Cellone | BSNL MOBILE",
          "Airtel ZM",
          "GEOCELL",
          "CMCC",
          "O2 - UK",
          "Oman Mobile",
          "Ifea",
          "GH MTN",
          "BSNL Mobilg",
          "stc ksa GREEN SAUDI",
          "ai tel",
          "O2 - SK",
          "JIO 4G",
          "Freedom",
          "Vi is here",
          "Pelephone",
          "UzMobile",
          "MAGTICOM",
          "Lycamobile",
          "StarHub",
          "CellOne | BSNL Mobile",
          "Vodafone IN | Vi",
          "404 04",
          "MoovAfricaGabonT",
          "Telia FI",
          "airteö",
          "TPG",
          "One NZ",
          "SummerTogether Mascom",
          "AirtelMadagascar",
          "Orange ML",
          "WINDTRE",
          "Chunghwa",
          "SMART",
          "IND airtel",
          "Ncell",
          "MOOV AFRICA",
          "LBR Lonestar Cell",
          "Beeline UZ",
          "ASIACELL",
          "JIO | Jio",
          "Renna",
          "Vi | airtel",
          "Dolphin-Mumbai",
          "_Φ_ _É_(",
          "AIRTEL DRC",
          "Vi India | zain BH",
          "ફક્ત તાત્કાલિક ક",
          "40405",
          "chatr",
          "Partner IL",
          "TELUS",
          "000000 | airtel",
          "RSA CELL C",
          "Mobitel | Idea",
          "Vi Intia",
          "VODAFONE CZ",
          "405870",
          "stc ksa Hajj Expo",
          "IN-DOLPHIN",
          "UCell",
          "Vodafone AU",
          "Glo LTE",
          " irtel",
        ],
        STATE: [
          "Andhra Pradesh",
          "Bihar",
          "Delhi",
          "Chhattisgarh",
          "Jammu and Kashmir",
          "Odisha",
          "Nagaland",
          "Himachal Pradesh",
          "Maharashtra",
          "Karnataka",
          "Jharkhand",
          "Tamil Nadu",
          "Andaman and Nicobar Islands",
          "Meghalaya",
          "Telangana",
          "Tripura",
          "Ladakh",
          "Puducherry",
          "Assam",
          "Punjab",
          "Rajasthan",
          "Uttarakhand",
          "Gujarat",
          "Goa",
          "Manipur",
          "Madhya Pradesh",
          "Kerala",
          "West Bengal",
          "Daman and Diu",
          "Arunachal Pradesh",
          "Mizoram",
          "Uttar Pradesh",
          "Haryana",
          "Sikkim",
          "Chandigarh",
          "Lakshadweep",
          "Dadra and Nagar Haveli",
        ],
        OS_VERSION: [
          "10.0",
          "10.1",
          "7.1",
          "5.1.1",
          "7.1.1",
          "S_V2",
          "TIRAMISU",
          "P",
          "6.0",
          "10",
          "N_MR1",
          "Q",
          "M",
          "R",
          "13",
          "12",
          "8.1",
          "6.0.1",
          "5.0.2",
          "11",
          "UPSIDE_DOWN_CAKE",
          "9",
          "O",
          "O_MR1",
          "VANILLA_ICE_CREAM",
          "7.0",
          "S",
          "LOLLIPOP_MR1",
          "14",
          "8.1.0",
          "7.1.2",
          "9.1",
          "15",
          "L",
          "8.0.0",
          "5.1",
          "N",
        ],
      }),
    );
  };
