#!/bin/bash
set -e  # Exit on error

# Log all output
exec > >(tee /var/log/user-data.log) 2>&1
echo "Starting user-data script at $(date)"

# Set environment variables persistently
# Write to /etc/environment for system-wide availability (systemd, all processes)
# Write to /etc/profile.d/ for interactive shell sessions
echo "Setting up environment variables..."

# Create /etc/environment entries (system-wide, no export needed)
ENV_FILE="/etc/environment"
# Backup existing file
if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$ENV_FILE.backup"
fi

# Remove existing Pulse environment variables to avoid duplicates
%{ for env_var in env_vars ~}
sed -i '/^${env_var.key}=/d' "$ENV_FILE" 2>/dev/null || true
%{ endfor ~}

# Append environment variables to /etc/environment
%{ for env_var in env_vars ~}
echo "${env_var.key}=${replace(env_var.value, "'", "'\\''")}" >> "$ENV_FILE"
%{ endfor ~}

# Create profile.d script for interactive shells
PROFILE_SCRIPT="/etc/profile.d/pulse-env.sh"
cat > "$PROFILE_SCRIPT" << 'PROFILE_HEADER'
# Pulse application environment variables
# This file is automatically generated by user-data script
PROFILE_HEADER

# Append export statements to profile.d script
%{ for env_var in env_vars ~}
echo "export ${env_var.key}='${replace(env_var.value, "'", "'\\''")}'" >> "$PROFILE_SCRIPT"
%{ endfor ~}

chmod 644 "$PROFILE_SCRIPT"

# Export in current session for use during script execution
%{ for env_var in env_vars ~}
export ${env_var.key}='${replace(env_var.value, "'", "'\\''")}'
%{ endfor ~}

# Update system packages
echo "Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

# Install required packages
echo "Installing required packages..."
apt-get install -y \
    git \
    curl \
    wget \
    unzip \
    ca-certificates \
    gnupg \
    lsb-release \
    nginx

# Install Node.js 20
echo "Installing Node.js 20..."
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs

# Verify Node.js installation
node --version
npm --version

# Install yarn globally
echo "Installing yarn..."
npm install -g yarn

# Verify yarn installation
yarn --version

# Clone the repository to /opt/bin
echo "Cloning pulse repository to /opt/bin..."
mkdir -p /opt/bin
cd /opt/bin
if [ -d "pulse" ]; then
    rm -rf pulse
fi
git clone https://github.com/dream-horizon-org/pulse.git
cd pulse

# Checkout main branch (ensure we're on main)
git checkout main

# Build the pulse-ui React application
echo "Building pulse-ui..."
cd pulse-ui

# Set build environment variables
export BABEL_ENV=production
export NODE_ENV=production

# REACT_APP_* variables are already exported from app_env above

# Install dependencies
echo "Installing dependencies..."
yarn install --frozen-lockfile

# Build the application
echo "Building React application..."
yarn build

# Verify build was successful
if [ ! -d "build" ]; then
    echo "ERROR: Build directory not found at pulse-ui/build"
    exit 1
fi

# Set up nginx to serve the built files
echo "Setting up nginx..."
NGINX_DIR="/opt/bin/pulse/pulse-ui/nginx"
NGINX_CONF="$NGINX_DIR/nginx.conf"
NGINX_PID="$NGINX_DIR/nginx.pid"

# Create nginx directory
mkdir -p "$NGINX_DIR"

# Create nginx configuration for React Router on port 3000
cat > "$NGINX_CONF" << NGINX_EOF
pid $NGINX_PID;
error_log $NGINX_DIR/error.log;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    access_log $NGINX_DIR/access.log;
    
    server {
        listen 3000;
        server_name _;
        
        root /opt/bin/pulse/pulse-ui/build;
        index index.html index.htm;
        
        location / {
            try_files \$uri \$uri/ /index.html;
        }
        
        location /healthcheck.txt {
            root /opt/bin/pulse/pulse-ui/build;
        }
        
        # Healthcheck endpoint for ALB
        location /healthcheck {
            access_log off;
            return 200 "healthy\n";
            add_header Content-Type text/plain;
        }
    }
}
NGINX_EOF

# Stop any existing nginx processes
pkill nginx || true
sleep 2

# Run nginx directly in the background
echo "Starting nginx on port 3000..."
nginx -c "$NGINX_CONF" &
sleep 2

# Get the PID from the pid file
if [ -f "$NGINX_PID" ]; then
    NGINX_PID_VALUE=$(cat "$NGINX_PID")
else
    # Fallback: find nginx process
    NGINX_PID_VALUE=$(pgrep -f "nginx.*$NGINX_CONF" | head -1)
fi

# Wait a moment for nginx to start
sleep 5

# Check if nginx is running
if [ -n "$NGINX_PID_VALUE" ] && ps -p "$NGINX_PID_VALUE" > /dev/null 2>&1; then
    echo "✓ nginx started successfully (PID: $NGINX_PID_VALUE)"
    
    # Check if port 3000 is listening
    if netstat -tlnp 2>/dev/null | grep -q ':3000' || ss -tlnp 2>/dev/null | grep -q ':3000'; then
        echo "✓ nginx is listening on port 3000"
    else
        echo "⚠ Warning: Port 3000 may not be listening yet"
    fi
    
    # Test healthcheck endpoint
    if curl -f http://localhost:3000/healthcheck.txt > /dev/null 2>&1; then
        echo "✓ Healthcheck endpoint is responding at http://localhost:3000/healthcheck.txt"
    else
        echo "⚠ Warning: Healthcheck endpoint may not be responding yet"
    fi
else
    echo "⚠ Warning: nginx may not have started properly"
    echo "Check error log at: $NGINX_DIR/error.log"
    if [ -f "$NGINX_DIR/error.log" ]; then
        echo "Recent error log output:"
        tail -n 50 "$NGINX_DIR/error.log" || true
    fi
fi

echo "User-data script completed at $(date)"
echo "Pulse UI should be running on port 3000"
echo "Application directory: /opt/bin/pulse/pulse-ui"
echo "Build directory: /opt/bin/pulse/pulse-ui/build"
echo "Nginx config: $NGINX_CONF"
echo "Nginx PID: $(cat $NGINX_PID 2>/dev/null || echo 'N/A')"
echo "Healthcheck: http://localhost:3000/healthcheck.txt"
echo "To check if running: ps -p \$(cat $NGINX_PID 2>/dev/null)"
echo "To view nginx error logs: tail -f $NGINX_DIR/error.log"
echo "To view nginx access logs: tail -f $NGINX_DIR/access.log"
echo "To view build logs: cat /var/log/user-data.log"
