apiVersion: 1
datasources:
  - name: Pulse OTEL (Prometheus)
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: false
    editable: true
    uid: pulse_otel_prometheus
