package in.horizonos.pulseserver.service.alert.core.models;

public enum Metric {
  APDEX,
  ERROR_RATE,
  INTERACTION_CATEGORY_POOR,
  INTERACTION_CATEGORY_AVERAGE,
  INTERACTION_CATEGORY_GOOD,
  INTERACTION_CATEGORY_EXCELLENT,
  INTERACTION_TIME_P99,
  INTERACTION_TIME_P95,
  INTERACTION_TIME_P50,
  SCREEN_LOAD_TIME_P99,
  SCREEN_LOAD_TIME_P95,
  SCREEN_LOAD_TIME_P50,
  SCREEN_DAILY_USERS,
  SCREEN_ACTIVE_USERS,
  SCREEN_ERROR_RATE,
}
