{
  "type": "record",
  "name": "OtelLog",
  "namespace": "org.dreamhorizon.pulses3archiver",
  "fields": [
    {"name": "Timestamp",          "type": {"type": "long", "logicalType": "timestamp-micros"}},
    {"name": "TraceId",            "type": "string"},
    {"name": "SpanId",             "type": "string"},
    {"name": "TraceFlags",         "type": "int"},
    {"name": "SeverityText",       "type": "string"},
    {"name": "SeverityNumber",     "type": "int"},
    {"name": "ServiceName",        "type": "string"},
    {"name": "Body",               "type": "string"},
    {"name": "ResourceSchemaUrl",  "type": "string"},
    {"name": "ResourceAttributes", "type": {"type": "map", "values": "string"}},
    {"name": "ScopeSchemaUrl",     "type": "string"},
    {"name": "ScopeName",          "type": "string"},
    {"name": "ScopeVersion",       "type": "string"},
    {"name": "ScopeAttributes",    "type": {"type": "map", "values": "string"}},
    {"name": "LogAttributes",      "type": {"type": "map", "values": "string"}},
    {"name": "SessionId",          "type": "string"},
    {"name": "MeteringSessionId",  "type": "string"},
    {"name": "ProjectId",          "type": "string"},
    {"name": "AppVersion",         "type": "string"},
    {"name": "SDKVersion",         "type": "string"},
    {"name": "Platform",           "type": "string"},
    {"name": "OsVersion",          "type": "string"},
    {"name": "GeoState",           "type": "string"},
    {"name": "GeoCountry",         "type": "string"},
    {"name": "DeviceModel",        "type": "string"},
    {"name": "NetworkProvider",    "type": "string"},
    {"name": "UserId",             "type": "string"},
    {"name": "AppInstallationId",  "type": "string"},
    {"name": "PulseType",          "type": "string"},
    {"name": "EventName",          "type": "string"},
    {"name": "ScreenName",         "type": "string"},
    {"name": "ClickType",          "type": "string"},
    {"name": "Rage",               "type": "boolean"},
    {"name": "RageCount",          "type": "int"},
    {"name": "XPer",               "type": "float"},
    {"name": "YPer",               "type": "float"},
    {"name": "NormXPer",           "type": "float"},
    {"name": "NormYPer",           "type": "float"},
    {"name": "ViewportWidth",      "type": "int"},
    {"name": "ViewportHeight",     "type": "int"},
    {"name": "AspectRatio",        "type": "string"},
    {"name": "WebVitalName",       "type": "string"},
    {"name": "WebVitalValue",      "type": "double"},
    {"name": "WebVitalRating",     "type": "string"},
    {"name": "Hour",               "type": "int"}
  ]
}
