{
  "type": "record",
  "name": "OtelTrace",
  "namespace": "org.dreamhorizon.pulses3archiver",
  "fields": [
    {"name": "Timestamp",         "type": {"type": "long", "logicalType": "timestamp-micros"}},
    {"name": "TraceId",           "type": "string"},
    {"name": "SpanId",            "type": "string"},
    {"name": "ParentSpanId",      "type": "string"},
    {"name": "TraceState",        "type": "string"},
    {"name": "SpanName",          "type": "string"},
    {"name": "SpanKind",          "type": "string"},
    {"name": "ServiceName",       "type": "string"},
    {"name": "ResourceAttributes","type": {"type": "map", "values": "string"}},
    {"name": "ScopeName",         "type": "string"},
    {"name": "ScopeVersion",      "type": "string"},
    {"name": "SpanAttributes",    "type": {"type": "map", "values": "string"}},
    {"name": "Duration",          "type": "long"},
    {"name": "StatusCode",        "type": "string"},
    {"name": "StatusMessage",     "type": "string"},
    {"name": "EventsTimestamp",   "type": {"type": "array", "items": {"type": "long", "logicalType": "timestamp-micros"}}},
    {"name": "EventsName",        "type": {"type": "array", "items": "string"}},
    {"name": "EventsAttributes",  "type": {"type": "array", "items": {"type": "map", "values": "string"}}},
    {"name": "LinksTraceId",      "type": {"type": "array", "items": "string"}},
    {"name": "LinksSpanId",       "type": {"type": "array", "items": "string"}},
    {"name": "LinksTraceState",   "type": {"type": "array", "items": "string"}},
    {"name": "LinksAttributes",   "type": {"type": "array", "items": {"type": "map", "values": "string"}}},
    {"name": "ProjectId",         "type": "string"},
    {"name": "SpanType",          "type": "string"},
    {"name": "PulseType",         "type": "string"},
    {"name": "SessionId",         "type": "string"},
    {"name": "AppVersion",        "type": "string"},
    {"name": "SDKVersion",        "type": "string"},
    {"name": "Platform",          "type": "string"},
    {"name": "OsVersion",         "type": "string"},
    {"name": "GeoState",          "type": "string"},
    {"name": "GeoCountry",        "type": "string"},
    {"name": "DeviceModel",       "type": "string"},
    {"name": "NetworkProvider",   "type": "string"},
    {"name": "MeteringSessionId", "type": "string"},
    {"name": "UserId",            "type": "string"},
    {"name": "AppInstallationId", "type": "string"},
    {"name": "HttpUrl",           "type": "string"},
    {"name": "HttpHost",          "type": "string"},
    {"name": "HttpMethod",        "type": "string"},
    {"name": "HttpStatusCode",    "type": "int"},
    {"name": "GraphqlType",       "type": "string"},
    {"name": "GraphqlName",       "type": "string"},
    {"name": "ScreenName",        "type": "string"},
    {"name": "Hour",              "type": "int"}
  ]
}
