{
  "type": "record",
  "name": "OtelMetricsSummary",
  "namespace": "org.dreamhorizon.pulses3archiver",
  "fields": [
    {"name": "ResourceAttributes",         "type": {"type": "map", "values": "string"}},
    {"name": "ResourceSchemaUrl",           "type": "string"},
    {"name": "ScopeName",                   "type": "string"},
    {"name": "ScopeVersion",               "type": "string"},
    {"name": "ScopeAttributes",            "type": {"type": "map", "values": "string"}},
    {"name": "ScopeDroppedAttrCount",      "type": "int"},
    {"name": "ScopeSchemaUrl",             "type": "string"},
    {"name": "ServiceName",                "type": "string"},
    {"name": "MetricName",                 "type": "string"},
    {"name": "MetricDescription",          "type": "string"},
    {"name": "MetricUnit",                 "type": "string"},
    {"name": "Attributes",                 "type": {"type": "map", "values": "string"}},
    {"name": "StartTimeUnix",              "type": {"type": "long", "logicalType": "timestamp-micros"}},
    {"name": "TimeUnix",                   "type": {"type": "long", "logicalType": "timestamp-micros"}},
    {"name": "Count",                      "type": "long"},
    {"name": "Sum",                        "type": "double"},
    {"name": "ValueAtQuantilesQuantile",   "type": {"type": "array", "items": "double"}},
    {"name": "ValueAtQuantilesValue",      "type": {"type": "array", "items": "double"}},
    {"name": "Flags",                      "type": "int"},
    {"name": "ProjectId",                  "type": "string"},
    {"name": "SessionId",                  "type": "string"},
    {"name": "MeteringSessionId",          "type": "string"},
    {"name": "AppVersion",                 "type": "string"},
    {"name": "SDKVersion",                 "type": "string"},
    {"name": "Platform",                   "type": "string"},
    {"name": "OsVersion",                  "type": "string"},
    {"name": "GeoState",                   "type": "string"},
    {"name": "GeoCountry",                 "type": "string"},
    {"name": "DeviceModel",                "type": "string"},
    {"name": "NetworkProvider",            "type": "string"},
    {"name": "UserId",                     "type": "string"},
    {"name": "Hour",                       "type": "int"}
  ]
}
