kafka {
  bootstrapServers = "pulse-kafka-01.pulse.local:9092,pulse-kafka-02.pulse.local:9092"
  bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}

  groupId = "pulse-s3-archiver"
  groupId = ${?KAFKA_GROUP_ID}

  clientId = "pulse-s3-archiver"
  clientId = ${?KAFKA_CLIENT_ID}

  autoOffsetReset = "earliest"
  autoOffsetReset = ${?KAFKA_AUTO_OFFSET_RESET}

  maxPollRecords = 2000
  maxPollRecords = ${?KAFKA_MAX_POLL_RECORDS}

  fetchMinBytes = 1048576
  fetchMinBytes = ${?KAFKA_FETCH_MIN_BYTES}

  fetchMaxWaitMs = 500
  fetchMaxWaitMs = ${?KAFKA_FETCH_MAX_WAIT_MS}

  topicTraces = "pulse.traces"
  topicTraces = ${?KAFKA_TOPIC_TRACES}

  topicLogs = "pulse.logs"
  topicLogs = ${?KAFKA_TOPIC_LOGS}

  topicMetrics = "pulse.metrics"
  topicMetrics = ${?KAFKA_TOPIC_METRICS}
}
