kafka {
  bootstrapServers = ${?KAFKA_BOOTSTRAP_SERVERS}
  bootstrapServers = "pulse-kafka-01.pulse.local:9092,pulse-kafka-02.pulse.local:9092"
  groupId = "pulse-s3-archiver"
  clientId = "pulse-s3-archiver"
  autoOffsetReset = "latest"
  maxPollRecords = 2000
  fetchMinBytes = 1048576
  fetchMaxWaitMs = 500
  topicTraces = "pulse.traces"
  topicLogs = "pulse.logs"
  topicMetrics = "pulse.metrics"
}
