s3 {
  rootBucket = "pulse-otel-ingestion"
  rootBucket = ${?S3_BUCKET}

  region = "ap-south-1"
  region = ${?S3_REGION}

  multipartThresholdBytes = 16777216
  multipartThresholdBytes = ${?S3_MULTIPART_THRESHOLD_BYTES}

  multipartPartBytes = 16777216
  multipartPartBytes = ${?S3_MULTIPART_PART_BYTES}

  maxConcurrency = 32
  maxConcurrency = ${?S3_MAX_CONCURRENCY}
}
