writer {
  rowGroupBytes = 134217728
  rowGroupBytes = ${?WRITER_ROW_GROUP_BYTES}

  pageBytes = 1048576
  pageBytes = ${?WRITER_PAGE_BYTES}

  compression = "ZSTD"
  compression = ${?WRITER_COMPRESSION}

  zstdLevel = 3
  zstdLevel = ${?WRITER_ZSTD_LEVEL}

  flushSizeBytes = 268435456
  flushSizeBytes = ${?WRITER_FLUSH_SIZE_BYTES}

  flushAgeMs = 300000
  flushAgeMs = ${?WRITER_FLUSH_AGE_MS}
}
