#!/bin/bash
set -e

exec > >(sudo tee /var/log/user-data.log) 2>&1
echo "Starting user-data script at $(date)"

cd /home/admin

# -------------------------------------------------------------------
# 1. Set environment variables
# -------------------------------------------------------------------
ENV_FILE="/etc/environment"

if [ -f "$ENV_FILE" ]; then
    cp "$ENV_FILE" "$ENV_FILE.backup"
fi

%{ for env_var in app_env ~}
sed -i '/^${env_var.key}=/d' "$ENV_FILE" 2>/dev/null || true
%{ endfor ~}

%{ for env_var in app_env ~}
echo "${env_var.key}=${replace(env_var.value, "'", "'\\''")}" >> "$ENV_FILE"
%{ endfor ~}

PROFILE_SCRIPT="/etc/profile.d/pulse-alerts-cron-env.sh"
cat > "$PROFILE_SCRIPT" << 'PROFILE_HEADER'
# Pulse Alerts Cron environment variables
# Automatically generated by user-data script
PROFILE_HEADER

%{ for env_var in app_env ~}
echo "export ${env_var.key}='${replace(env_var.value, "'", "'\\''")}'" >> "$PROFILE_SCRIPT"
%{ endfor ~}

chmod 644 "$PROFILE_SCRIPT"

%{ for env_var in app_env ~}
export ${env_var.key}='${replace(env_var.value, "'", "'\\''")}'
%{ endfor ~}

# -------------------------------------------------------------------
# 2. Download artifact from CodeArtifact
# -------------------------------------------------------------------
AWS_REGION="ap-south-1"
CODEARTIFACT_DOMAIN="pulse-prod"
CODEARTIFACT_REPOSITORY="pulse-alerts-cron"
APPLICATION_NAME="pulse-alerts-cron"
VERSION=${artifact_version}

echo "Downloading $APPLICATION_NAME version $VERSION from CodeArtifact..."
aws codeartifact get-package-version-asset \
  --region "$AWS_REGION" \
  --domain "$CODEARTIFACT_DOMAIN" \
  --repository "$CODEARTIFACT_REPOSITORY" \
  --format generic \
  --namespace "pulse" \
  --package "$APPLICATION_NAME" \
  --package-version "$VERSION" \
  --asset "$APPLICATION_NAME-$VERSION.zip" \
  "$APPLICATION_NAME.zip"

# -------------------------------------------------------------------
# 3. Unzip and verify artifact
# -------------------------------------------------------------------
unzip "$APPLICATION_NAME.zip"

APP_DIR="/home/admin/$APPLICATION_NAME"

if [ ! -f "$APP_DIR/pulse-alerts-cron.jar" ]; then
    echo "ERROR: JAR file not found at $APP_DIR/pulse-alerts-cron.jar"
    exit 1
fi

# -------------------------------------------------------------------
# 4. Start the application
# -------------------------------------------------------------------
echo "Starting pulse-alerts-cron..."

nohup java \
    -jar $APP_DIR/pulse-alerts-cron.jar \
    run org.dreamhorizon.pulsealertscron.verticle.MainVerticle \
    > /home/admin/pulse-alerts-cron.log 2>&1 &

echo $! > /home/admin/pulse-alerts-cron.pid

sleep 10

if ps -p $(cat /home/admin/pulse-alerts-cron.pid) > /dev/null 2>&1; then
    echo "pulse-alerts-cron started successfully (PID: $(cat /home/admin/pulse-alerts-cron.pid))"

    echo "Waiting for application to be ready..."
    sleep 15

    if netstat -tlnp 2>/dev/null | grep -q ':4000' || ss -tlnp 2>/dev/null | grep -q ':4000'; then
        echo "Application is listening on port 4000"
    else
        echo "Warning: Port 4000 may not be listening yet"
    fi
else
    echo "Warning: pulse-alerts-cron may not have started properly"
    echo "Check logs at: /home/admin/pulse-alerts-cron.log"
    if [ -f /home/admin/pulse-alerts-cron.log ]; then
        echo "Recent log output:"
        tail -n 50 /home/admin/pulse-alerts-cron.log || true
    fi
fi

echo "User-data script completed at $(date)"
echo "Log file: /home/admin/pulse-alerts-cron.log"
echo "PID file: /home/admin/pulse-alerts-cron.pid"
